# Generated by Django 5.2.7 on 2025-11-03 09:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=120, verbose_name='Прізвище')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'customers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Назва')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='store.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Адреса доставки'), ('billing', 'Адреса для рахунку')], max_length=20, verbose_name='Тип адреси')),
                ('street', models.CharField(max_length=255, verbose_name='Вулиця')),
                ('city', models.CharField(max_length=120, verbose_name='Місто')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Поштовий індекс')),
                ('country', models.CharField(default='Україна', max_length=120, verbose_name='Країна')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='store.customer', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Адреса клієнта',
                'verbose_name_plural': 'Адреси клієнтів',
                'db_table': 'customer_addresses',
                'ordering': ['customer', 'address_type'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('status', models.CharField(choices=[('pending', 'Очікування'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Загальна сума')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='store.customer', verbose_name='Клієнт')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='shipping_orders', to='store.customeraddress', verbose_name='Адреса доставки')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Сума')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Карткою'), ('bank_transfer', 'Банківський переказ'), ('online', 'Онлайн оплата')], max_length=20, verbose_name='Спосіб оплати')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('completed', 'Завершено'), ('failed', 'Не вдалося'), ('refunded', 'Повернено')], default='pending', max_length=20, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакції')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='store.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Платежі',
                'db_table': 'payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=160, verbose_name='Назва')),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ціна')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Знижка (%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store.category', verbose_name='Категорія')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.supplier', verbose_name='Постачальник за замовчуванням')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кількість')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ціна за одиницю')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='store.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
                'db_table': 'order_items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата відправлення')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('carrier', models.CharField(max_length=120, verbose_name='Перевізник')),
                ('tracking_number', models.CharField(max_length=120, unique=True, verbose_name='Номер відстеження')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('in_transit', 'В дорозі'), ('delivered', 'Доставлено'), ('returned', 'Повернуто')], default='pending', max_length=20, verbose_name='Статус')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='shipment', to='store.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Відправлення',
                'verbose_name_plural': 'Відправлення',
                'db_table': 'shipments',
                'ordering': ['-shipment_date'],
            },
        ),
    ]
