# Generated by Django 5.2.7 on 2025-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристики'),
        ),
    ]
